### ISSUE TITLE
Question about the tachycardiac homework

### ISSUE THREAD

**Issue by MingzheHu-Duke** [dward2/BME547#210]
Hi, I have a question regarding one of the specification of the tarchycardiac homework. It says, "This String will only contain a single word, but there is no guarantee whether the word will be upper case, lower case, mixed case, or have leading / trailing spaces or punctuation.” “If the string contains the word ‘tachycardic’, return True.”. What does the “contains” mean here? IAre inputs like “tarchycardiacally” also supposed to return True or after the string is formatted (case, punctuations, spaces), it should be exacly the same as “tachycardic”? For example, “Tachy,cardiac ”.

**Comment by dward2** [comment]
@MingzheHu-Duke I just saw that you had posted this issue in the BME547 class repository.  In the future, open up your issue in your GitHub Classroom repository so that if I need to see you code, I will see it.  Also, be sure to add me as an "Assignee".  Or, if you don't have permission to do that, tag me by typing @dward2 in the message.
