### ISSUE TITLE
Question about tachycardic Homework 

### ISSUE THREAD

**Issue by anb72** [dward2/BME547#211]
I split up my function into two functions however I am still having issues with my tests running correctly also I am not entirely sure how to test an input function. Lastly neither True nor False is printing out when I test my function. 
Code: 
`def is_tachycardic():
    print("Diagnosis Checker Tool")
    print("")
    print("Please enter condition below")
    condition = str(input("Enter condition to be checked: ")).lower().strip()
    return condition
    

def condition_check(condition):
    if condition == "tachycardic":
        print("True")
        return True
    else:
        print("False")
        return False 

if __name__ == "__main__":
    is_tachycardic()
`

Test: 
`import pytest

@pytest.mark.parametrize("condition","expected", [
    ("tachycardic",True),
    ("Tachycardic",True),
    (" Tachycardic",True),
    ("tachycardic   ",True),
    ("taChycardic  ",True),
    ("cancer",False),
    ("anemia",False),
    ])

def test_condition_check(condition, expected):
    from tachycardia import condition_check
    answer = condition_check(condition)
    assert answer == expected

def test_is_tachycardic():
    from tachycardia import is_tachycardic
    answer = is_tachycardic`

**Comment by dward2** [comment]
@anb72 Adrianna,  thanks for posting this issue.  Note that, in the future, please post issues in your GitHub Classroom repository, rather than here.  In that way, it easier for me to see your code.  Also, make sure to make me either an Assignee or tag me with @dward2 so I will get notification of your issue.  But, since you had sent your e-mail, I knew to go looking.  

You are on the correct track.  Let's look at your two functions.  
```python
def is_tachycardic():
    print("Diagnosis Checker Tool")
    print("") 
    print("Please enter condition below")
    condition = str(input("Enter condition to be checked: ")).lower().strip()
    return condition
```
This function allows a user to enter a string.  It then does some manipulation on the string and returns the string to the function that called it.

Your other function is:
```python
def condition_check(condition):
    if condition == "tachycardic":
        print("True")
        return True
    else:
        print("False")
        return False
```
This function checks to see if the word it is sent as a parameter is the target word.

Let's look at the assignment.  It is asking for a function that is sent a parameter and returns True or False for whether the word is tachycardic.  Which of your two functions above meets that description?

**Comment by anb72** [comment]
I would say that the condition_check function does that

**Comment by dward2** [comment]
I saw that you have some more recent code in your repository.  I'm going to move the discussion there.

**Comment by anb72** [comment]
could I use a method similar to the one for the fruit check example in class where I ask for the input in the if name=main statement and in condition_check I have a list of acceptable answers to check against.

**Comment by dward2** [comment]
Yes, you definitely could move the input into the name == main statement.  This way, you can still get user input for testing your function, but it won't be access when running the test.

But, the problem with having a list of acceptable answers to check is that the possible options are way too high.  So, let's look at the code you have already written.  What exists that helps understand if the string meets the needed criteria?

**Comment by anb72** [comment]
the .lower.strip on the input

**Comment by dward2** [comment]
Yep.  I'm logging off now.  But, see if you can put all of that together in such a way that you can test it.
And, I might suggest that sometime this week, we might want to make an appointment and go through the code in more detail to make sure you understand it well before the next homework.  See you in class tomorrow.

**Comment by anb72** [comment]
Ok thank you Dr. Ward.! See you in class tommorow.
