### ISSUE TITLE
Question about cpap assignment

### ISSUE THREAD

**Issue by dylcai85** [dward2/BME547#415]
Hi Dr. Ward,
I have a question about the cpap homework assignment listed below:

My code created 10 different json files, one for each patient as the assignment specifies. Should I push these files to GitHub? Or should I put them in the .gitignore?

Thanks,
Dylan

**Comment by dward2** [comment]
@dylcai85 First, I will not see any issues you post (either in your GitHub Classroom repositories or in this repository) if you do not either "assign" me to the issue or tag me using @dward2.   I only saw this issue because I happened to go into my issues for another reason.  So, please always remember to assign me to an issue so I will receive notification about it.

As to your question, it is up to you whether you want to push them to GitHub.  I have no plans to look at or evaluate any `.json` files you push up.  But, if I do have problems with running your code, and I see that you do have some output files there, that could possibly help me figure out what is happening.  At the same time, if you do add them to your repository, it could be annoying for you to continually have to update your repository anytime those files change if you are still working on your code.    Again, in the end, up to you, but it is not a requirement.
