### ISSUE TITLE
Question about Unit Testing & Continuous Integration assignment

### ISSUE THREAD

**Issue by North-M** [dward2/BME547#516]
Can we consider that a valid email always starts and ends with spaces? In other words, if the prefix or the toplevel contains unwanted characters, should we consider it as invalid?

For example, if a string is pre+fix@domain.top.level, should we consider it as invalid, or we can extract the middle part: fix@domain.top and treat as valid?

**Comment by dward2** [comment]
@North-M I know we answered this by e-mail, but I wanted to follow up on this post.  Since you did not assign this issue to me, I never received notification that you had made this post until I stumbled across it this morning.  So, if you want me to be aware of an Issue posting, please remember to add me as the Assignee by selecting my name in Assignees to the right of this screen.

Also, when asking a question about a particular homework assignment, it is best to open up your Issue in your repository for that work so that we can easily refer to the work you are doing.  For general questions, though, it is fine to make a posting here.  Just remember to add me as an assignee and that this is an open forum so do not post any personal information related to your specific work.
